---
title: "main"
format: html
editor: visual
knitr:
  opts_chunk:
    fig.align: center
---

## 3007 Team Cyan Group Project

Group 3 (CYAN) Members:\
Kahbelan Kalisalvam Kelaver\
Poh Kai Boon\
Goh Yee Kit\
Lau Hui Qi\
See Kai Cong\
Joel Yong\

## Main code

```{r}
#| output: false
# Load necessary libraries
library(dplyr)
library(ggplot2)
library(tidyverse)
library(readxl)
library(lubridate)
library(DT)
library(sf)
```

```{r}
#| label: data import
#| output: false
# Set the path to the CSV file
file_path <- "Crime_Data_from_2020_to_Present_20240607.csv"

# Read the CSV file into a data frame
crime_data <- read.csv(file_path)

# View the first few rows of the data
head(crime_data)
```

```{r}
#| label: data-cleaning - keep selected column
#| output: false

crime_data <- crime_data |>
  select(Date.Rptd, DATE.OCC, TIME.OCC, AREA, AREA.NAME, Rpt.Dist.No, Crm.Cd, Crm.Cd.Desc, Crm.Cd.1, Crm.Cd.2, Crm.Cd.3, Crm.Cd.4, LOCATION, Cross.Street, LAT, LON)

# View the first few rows of the modified data
head(crime_data)
```

```{r}
#| label: data cleaning - remove rows if null for certain column, remove multiple spaces if any

# Remove rows with NA values in the specified columns
cleaned_crime_data <- crime_data %>%
  filter(
    !is.na(Date.Rptd) &
    !is.na(DATE.OCC) &
    !is.na(TIME.OCC) &
    !is.na(AREA) &
    !is.na(AREA.NAME) &
    !is.na(Rpt.Dist.No) &
    !is.na(LOCATION) &
    !is.na(LAT) &
    !is.na(LON)
  )

# Function to replace multiple spaces with a single space in a string
replace_multiple_spaces <- function(x) {
  gsub("\\s+", " ", x)
}

# Apply the function to all character columns in the data frame
cleaned_crime_data <- cleaned_crime_data %>%
  mutate(across(where(is.character), replace_multiple_spaces))

# View the first few rows of the cleaned data
head(cleaned_crime_data)
```

```{r}
#| label: data-formating

# Convert DATE.OCC to Date format
cleaned_crime_data$DATE.OCC <- as.Date(cleaned_crime_data$DATE.OCC, format="%m/%d/%Y %I:%M:%S %p")

# Extract month and year from DATE.OCC
cleaned_crime_data <- cleaned_crime_data %>%
  mutate(
    DATE.OCC.MONTH = month(DATE.OCC),
    DATE.OCC.YEAR = year(DATE.OCC)
  )

cleaned_crime_data <- cleaned_crime_data %>%
  select(Date.Rptd, DATE.OCC, DATE.OCC.MONTH, DATE.OCC.YEAR, everything())

# View the first few rows of the cleaned data with new columns
datatable(head(cleaned_crime_data))
```

```{r}
#| label: data-preparation
#| message: false

#Counts of crime in each area
crime_counts_by_area <- cleaned_crime_data %>%
  mutate(AREA.NAME = toupper(AREA.NAME)) %>%
  group_by(AREA, AREA.NAME) %>%
  summarise(Crime_Count = n(), .groups = 'drop')

crime_counts_by_area[8, "AREA.NAME"] <- "WEST LOS ANGELES"
crime_counts_by_area[15, "AREA.NAME"] <- "NORTH HOLLYWOOD"

crime_counts_by_area
```

```{r}
#Based of crime code, find top 5 crime codes and the corresponding crime description based on each area
top_crime_codes_by_area <- cleaned_crime_data %>%
  mutate(AREA.NAME = toupper(AREA.NAME)) %>%
  mutate(
    AREA.NAME = replace(AREA.NAME, AREA == 8, "WEST LOS ANGELES"), # Fix Short Form Names
    AREA.NAME = replace(AREA.NAME, AREA == 15, "NORTH HOLLYWOOD"),
    AREA.NAME = replace(AREA.NAME, AREA == 3, "SOUTHWEST"), # Fix AREA with wrong names
  ) %>%
  group_by(AREA, AREA.NAME, Crm.Cd, Crm.Cd.Desc) %>%
  summarise(Crime_Count = n(), .groups = 'drop') %>%
  arrange(desc(Crime_Count)) %>%
  group_by(AREA, AREA.NAME) %>%
  slice_head(n = 5)

top_crime_codes_by_area
```

```{r}
#| label: data-visualisation - total crimes by area
#| message: false

#Plot the number of crimes in each area in a map
crime_counts_by_area_map <- crime_counts_by_area %>%
  ggplot(aes(x = AREA, y = AREA.NAME, size = Crime_Count)) +
  geom_point(aes(colour = Crime_Count), alpha = 0.7) +
  scale_size_continuous(range = c(2, 12)) +
  labs(title = "Number of Crimes in Each Area", x = "Area", y = "Area Name") +
  theme_minimal()

crime_counts_by_area_map
```

```{r}
#| label: data-preparation - centroids
#| warning: false

la <- st_read("City_Boundary.geojson")

la_centroids <- la %>%
  st_centroid() %>%
  rename(centroids = geometry) %>%
  st_coordinates() %>%
  as.data.frame() %>%
  setNames(c("long_center", "lat_center")) %>%
  mutate(APREC = la$APREC)

# Join the total crime counts by area with the centroids
la_count <- la %>%
  left_join(crime_counts_by_area, by = c("APREC" = "AREA.NAME", "PREC" = "AREA")) %>%
  left_join(la_centroids, by = c("APREC" = "APREC"))

# Join the top crime codes by area with the centroids
top_crimes_la_count <- top_crime_codes_by_area %>%
  left_join(la, by = c("AREA.NAME" = "APREC", "AREA" = "PREC")) %>%
  left_join(la_centroids, by = c("AREA.NAME" = "APREC"))
```

```{r}
#| label: data-preparation - jitter coords for top 5 crimes

# Define the number of points and radius for the circular spread
n_points <- 5  # Number of top crimes
radius <- 4000  # Radius for the spread

# Function to generate circular points around a centroid
generate_circular_points <- function(lon, lat, n_points, radius) {
  angles <- seq(0, 2 * pi, length.out = n_points + 1)[-1]
  tibble(
    jittered_long = lon + radius * cos(angles),
    jittered_lat = lat + radius * sin(angles)
  )
}

# Generate circular points for each row in the dataset
top_crimes_la_count <- top_crimes_la_count %>%
  group_by(AREA) %>%
  mutate(id = row_number()) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(
    circular_coords = list(generate_circular_points(long_center, lat_center, n_points, radius)),
    jittered_long = circular_coords$jittered_long[id],
    jittered_lat = circular_coords$jittered_lat[id]
  ) %>%
  select(-circular_coords, -id) %>%
  ungroup()
```

```{r}
#| label: data-preparation - jitter coords for top 5 crimes (alternative)
top_crimes_la_count <- top_crimes_la_count %>%
  group_by(AREA) %>%
  mutate(
    rank = rank(Crime_Count),
    jittered_long = long_center - 5000,
    jittered_lat = lat_center - 10000 + rank * 3000
  ) %>%
  ungroup()
```

```{r fig.height=15, fig.width=15}
#| label: data-visualisation - number of top 5 crimes by area map

# Plot the top 5 crime codes in each area map with jittered points
top_crime_codes_by_area_map <- top_crime_codes_by_area %>%
  ggplot(aes(x = AREA, y = AREA.NAME, size = Crime_Count, colour = factor(Crm.Cd.Desc))) +
  geom_point(alpha = 0.5, position = position_jitter(width = 0.9, height = 0.8)) +
  scale_size_continuous(name = "Crime Count", range = c(2, 12)) +
  scale_colour_viridis_d(name = "Crime Type", option = "turbo", begin = 0.6, end = 1) +
  labs(title = "Number of Top 5 Crimes in Each Area", x = "Area", y = "Area Name") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 25, face = "bold"),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10)
  )

# Display the plot
top_crime_codes_by_area_map
```

```{r fig.height=15, fig.width=15}
#| label: data-visualisation - number of top 5 crimes and total crimes by area using geom_sf

# Define a set of shapes to use
shape_values <- c("\U1F52A", "\U1F44A", "\U1F3E0", "\U1F513", "\U1F494", "\U1F6CD", "\U1F3AD", "\U1F4B8", "\U1F58C", "\U1F693")

# Plot the number of top 5 crimes and total crimes in each area map using geom_sf
top_crime_codes_by_area_map_sf <- ggplot() +
  geom_sf(data = la_count, aes(fill = Crime_Count)) +
  geom_point(data = la_count, aes(x = long_center - 500, y = lat_center - 500), color = "black", size = 3, show.legend = FALSE) +
  geom_point(data = top_crimes_la_count, 
             aes(x = jittered_long , y = jittered_lat, shape = factor(Crm.Cd.Desc)), size = 3.5) +
  geom_segment(data = top_crimes_la_count, aes(x = long_center, y = lat_center, xend = jittered_long, yend = jittered_lat),
               color = "black") +
  scale_shape_manual(name = "Crime Type", values = shape_values) +
#  scale_size_continuous(name = "Crime Count per Crime Type",
#                        range = c(5, 5)) +
  scale_fill_gradient(low = "#fee8c8",
                      high = "#e34a33",
                      name = "Total Crime Count",
                      limits = c(25000, 65000),
                      breaks = c(30000, 40000, 50000, 60000),
                      labels = c("30k", "40k", "50k", "60k")) +
#  scale_colour_viridis_c(name = "Crime Count per Crime Type",
#                         option = "turbo",
#                         begin = 0.7,
#                         end = 1) +
#  labs(title = "Number of Top 5 Crimes and Total Crimes in Each Area of Los Angeles (LA)") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 25, face = "bold"),
    axis.title.x = element_blank(),  
    axis.title.y = element_blank(),  
    axis.text.x = element_blank(),   
    axis.text.y = element_blank(),   
    axis.ticks.x = element_blank(),  
    axis.ticks.y = element_blank(),  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),
    legend.title = element_text(size = 15),  
    legend.text = element_text(size = 15)
  ) +
  guides(shape = guide_legend(override.aes = list(size = 6)),  # Adjust the size of the shapes in the legend
         colour = guide_legend(override.aes = list(size = 6)))  # Adjust the size of the points in the legend

# Display the plot
top_crime_codes_by_area_map_sf
```
<<<<<<< Updated upstream
=======
```{r}
# Define a named vector with the abbreviations
abbreviations <- c(
  "MISSION" = "MIS",
  "DEVONSHIRE" = "DEV",
  "FOOTHILL" = "FTH",
  "TOPANGA" = "TOP",
  "WEST VALLEY" = "WVA",
  "NORTH HOLLYWOOD" = "NHO",
  "VAN NUYS" = "VNY",
  "NORTHEAST" = "NRT",
  "HOLLYWOOD" = "HOL",
  "WEST LOS ANGELES" = "WLA",
  "HOLLENBECK" = "HOL",
  "RAMPART" = "RAM",
  "WILSHIRE" = "WIL",
  "OLYMPIC" = "OLY",
  "SOUTHWEST" = "SW",
  "NEWTON" = "NEW",
  "PACIFIC" = "PAC",
  "77TH STREET" = "77S",
  "SOUTHEAST" = "SEA",
  "HARBOR" = "HAR",
  "CENTRAL" = "CEN"
)

# Add a new column with abbreviations
la_count <- la_count %>%
  mutate(AREA_ABBREV = abbreviations[APREC])

# Check the modified la_count table
print(la_count)
```

```{r fig.height=25, fig.width=20}
# Load the required packages
library(pals)
library(RColorBrewer)
library(ggrepel)

# Define a set of colors to use for each crime type from the pals package
color_values <- glasbey(n = 10)
glasbey_colors <- glasbey()

# Define the indices of colors to replace and their new values
replace_indices <- c(2, 3,4, 8, 6, 5, 9)  # Indices of the colors you want to replace
new_colors <- c("#00FF00", "#911eb4","#ff00f2", "#dcbeff", "#aaffc3","#131342","#42d4f4")  # New colors to replace the existing ones

# Replace specific colors
custom_colors <- glasbey_colors
custom_colors[replace_indices] <- new_colors

# Ensure the palette has exactly 10 colors by selecting the first 10 colors after replacement
custom_colors <- custom_colors[1:10]

# Plot the number of top 5 crimes and total crimes in each area map using geom_sf
top_crime_codes_by_area_map_sf <- ggplot() +
  geom_sf(data = la_count, aes(fill = Crime_Count)) +
  geom_segment(data = top_crimes_la_count, 
               aes(x = long_center, y = lat_center, xend = jittered_long, yend = jittered_lat, color = factor(Crm.Cd.Desc))) + 
  geom_point(data = la_count, aes(x = long_center - 500, y = lat_center - 500), color = "black", size = 3, show.legend = FALSE) +
  geom_point(data = top_crimes_la_count, 
             aes(x = jittered_long, y = jittered_lat, color = factor(Crm.Cd.Desc)), 
             size = 6) +  # Use shape 21 to allow both fill and color
  geom_point(data = top_crimes_la_count, 
             aes(x = jittered_long, y = jittered_lat), 
             color = "black", size = 5 + 1, shape = 21, stroke = 1, show.legend = FALSE) +  geom_text_repel(data = la_count, 
                  aes(x = long_center, y = lat_center, label = AREA_ABBREV), 
                  color = ifelse(la_count$Crime_Count > 45000, "white", "black"), 
                  size = 5, show.legend = FALSE, fontface = "bold",
                  nudge_y = 0.5, 
                  nudge_x = 0.5) +  # Add geom_text_repel for area labels
  scale_color_manual(name = "Crime Type", values = custom_colors) +  # Use color_manual for points and segments
  scale_fill_distiller(palette = "OrRd", 
                       name = "Total Crime Count",
                       limits = c(25000, 65000),
                       breaks = c(30000, 40000, 50000, 60000),
                       labels = c("30k", "40k", "50k", "60k"),
                       direction = 1) +
  theme_minimal() +
  labs(title = "Top 3 Crimes and Total Crimes by Area in Los Angeles") +
  theme(
    plot.title = element_text(size = 25, face = "bold", hjust = 0.5), 
    axis.title.x = element_blank(),  
    axis.title.y = element_blank(),  
    axis.text.x = element_blank(),   
    axis.text.y = element_blank(),   
    axis.ticks.x = element_blank(),  
    axis.ticks.y = element_blank(),  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),
    legend.title = element_text(size = 15),  
    legend.text = element_text(size = 15),
    legend.position = "bottom",  # Move legends to the bottom
  ) +
  guides(
    color = guide_legend(override.aes = list(size = 6)),  # Adjust the size of the points in the legend
    fill = guide_colorbar(barwidth = 10, barheight = 1)  # Adjust the size of the color bar legend
  )  # Adjust the size of the points in the legend

# Display the plot
top_crime_codes_by_area_map_sf
```
```{r}
# Get all the color codes from the glasbey palette
glasbey_colors <- glasbey()

# Print the color codes to identify which ones to exclude
print(glasbey_colors)

```







>>>>>>> Stashed changes
